IMAGE_NAME = "bento/ubuntu-24.04"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "zabbix" do |zabbix|
    zabbix.vm.box = IMAGE_NAME
    zabbix.vm.hostname = "zabbix-server"

    # SSH
	zabbix.vm.network "forwarded_port", guest: 22, host: 2225, host_ip: "127.0.0.1"



    # Web GUI
    zabbix.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

	zabbix.vm.provision "shell", path: "provision.sh"

  end
end
